-- Private, invitation-only Texas Hold'em storage for dp.horizonpivots.com.
--
-- The application is server authoritative. Browser clients never receive table
-- grants and never read the private schema. Invitation/session/rate-limit values
-- are HMAC-SHA256 digests generated by the Next.js server; plaintext room codes
-- and guest tokens are never stored here.

begin;

create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to service_role;

create or replace function private.dp_public_payload_is_safe(p_payload jsonb)
returns boolean
language sql
immutable
strict
security invoker
set search_path = ''
as $$
  with recursive nodes(value) as (
    select p_payload
    union all
    select child.value
    from nodes as node
    cross join lateral (
      select object_entry.value
      from jsonb_each(
        case
          when jsonb_typeof(node.value) = 'object' then node.value
          else '{}'::jsonb
        end
      ) as object_entry
      union all
      select array_entry.value
      from jsonb_array_elements(
        case
          when jsonb_typeof(node.value) = 'array' then node.value
          else '[]'::jsonb
        end
      ) as array_entry
    ) as child
  )
  select
    jsonb_typeof(p_payload) = 'object'
    and not exists (
      select 1
      from nodes as node
      cross join lateral jsonb_object_keys(
        case
          when jsonb_typeof(node.value) = 'object' then node.value
          else '{}'::jsonb
        end
      ) as object_key(key)
      where regexp_replace(lower(object_key.key), '[^a-z0-9]', '', 'g')
        ~ '(deck|holecards?|roomcode|codehash|token|secret|clerk|seed)'
    );
$$;

create or replace function private.dp_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.dp_rooms (
  id uuid primary key default gen_random_uuid(),
  public_id uuid not null unique default gen_random_uuid(),
  code_hash text not null unique
    check (code_hash ~ '^[0-9a-f]{64}$'),
  broadcast_topic text not null unique
    default encode(gen_random_bytes(24), 'hex')
    check (broadcast_topic ~ '^[0-9A-Za-z_-]{32,96}$'),
  owner_clerk_user_id text not null
    check (char_length(owner_clerk_user_id) between 1 and 128),
  status text not null default 'lobby'
    check (status in ('lobby', 'active', 'paused', 'closed', 'expired')),
  locked boolean not null default false,
  pause_after_hand boolean not null default false,
  spectators_enabled boolean not null default false,
  max_seats smallint not null default 6
    check (max_seats between 2 and 9),
  starting_stack bigint not null default 10000
    check (starting_stack between 2 and 1000000000),
  small_blind bigint not null default 50
    check (small_blind between 1 and 100000000),
  big_blind bigint not null default 100
    check (big_blind between 2 and 200000000),
  action_timeout_seconds smallint not null default 45
    check (action_timeout_seconds between 10 and 180),
  version bigint not null default 0
    check (version >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours'),
  closed_at timestamptz,
  constraint dp_rooms_blinds_check check (big_blind >= small_blind),
  constraint dp_rooms_stack_check check (starting_stack >= big_blind * 2),
  constraint dp_rooms_expiry_check check (
    expires_at > created_at
    and expires_at <= created_at + interval '12 hours'
  ),
  constraint dp_rooms_closed_at_check check (
    (status in ('closed', 'expired') and closed_at is not null)
    or (status not in ('closed', 'expired'))
  )
);

-- A constant-expression partial unique index serializes the one-open-room rule
-- even when two Vercel instances attempt to create a room concurrently.
create unique index dp_rooms_one_open_room_idx
  on public.dp_rooms ((1))
  where status in ('lobby', 'active', 'paused');

create index dp_rooms_expiry_idx
  on public.dp_rooms (expires_at)
  where status in ('lobby', 'active', 'paused');

create table public.dp_participants (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.dp_rooms(id) on delete cascade,
  kind text not null default 'guest'
    check (kind in ('owner', 'guest')),
  clerk_user_id text,
  display_name text not null
    check (
      char_length(display_name) between 1 and 24
      and display_name = btrim(display_name)
      and display_name !~ '[[:cntrl:]]'
    ),
  role text not null default 'player'
    check (role in ('player', 'spectator')),
  seat smallint check (seat between 1 and 9),
  stack bigint not null default 0 check (stack >= 0),
  connected boolean not null default true,
  ready boolean not null default false,
  sitting_out boolean not null default false,
  status text not null default 'joined'
    check (
      status in (
        'joined',
        'ready',
        'active',
        'sitting_out',
        'folded',
        'all_in',
        'left',
        'kicked'
      )
    ),
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  left_at timestamptz,
  unique (id, room_id),
  constraint dp_participants_identity_check check (
    (kind = 'owner' and clerk_user_id is not null)
    or (kind = 'guest' and clerk_user_id is null)
  ),
  constraint dp_participants_role_seat_check check (
    (role = 'player' and seat is not null)
    or (role = 'spectator' and seat is null and stack = 0)
  ),
  constraint dp_participants_left_at_check check (
    (status in ('left', 'kicked') and left_at is not null)
    or status not in ('left', 'kicked')
  )
);

create unique index dp_participants_active_seat_idx
  on public.dp_participants (room_id, seat)
  where seat is not null and status not in ('left', 'kicked');

create unique index dp_participants_active_name_idx
  on public.dp_participants (room_id, lower(display_name))
  where status not in ('left', 'kicked');

create unique index dp_participants_owner_idx
  on public.dp_participants (room_id)
  where kind = 'owner';

create index dp_participants_room_status_idx
  on public.dp_participants (room_id, status, seat);

create table public.dp_public_state (
  room_id uuid primary key references public.dp_rooms(id) on delete cascade,
  version bigint not null default 0 check (version >= 0),
  kind text not null default 'room_created'
    check (kind ~ '^[a-z][a-z0-9_]{0,39}$'),
  state jsonb not null default '{}'::jsonb
    check (private.dp_public_payload_is_safe(state)),
  updated_at timestamptz not null default now()
);

create table public.dp_action_log (
  action_id uuid primary key,
  room_id uuid not null references public.dp_rooms(id) on delete cascade,
  participant_id uuid,
  action_kind text not null
    check (action_kind ~ '^[a-z][a-z0-9_]{0,39}$'),
  request_hash text not null
    check (request_hash ~ '^[0-9a-f]{64}$'),
  expected_version bigint not null check (expected_version >= 0),
  resulting_version bigint not null check (resulting_version > expected_version),
  metadata jsonb not null default '{}'::jsonb
    check (private.dp_public_payload_is_safe(metadata)),
  created_at timestamptz not null default now(),
  constraint dp_action_log_participant_fk
    foreign key (participant_id, room_id)
    references public.dp_participants(id, room_id)
    on delete set null (participant_id)
);

create index dp_action_log_room_version_idx
  on public.dp_action_log (room_id, resulting_version desc);

create index dp_action_log_created_idx
  on public.dp_action_log (created_at);

create table public.dp_chat_messages (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.dp_rooms(id) on delete cascade,
  participant_id uuid not null,
  kind text not null default 'text'
    check (kind in ('text', 'reaction')),
  content text not null
    check (
      char_length(content) between 1 and 240
      and content = btrim(content)
      and content !~ '[[:cntrl:]]'
      and content !~* '(https?://|www\.|[[:alnum:]-]+(\.[[:alnum:]-]+)*\.[[:alpha:]]{2,}([/:?#]|$))'
      and (kind <> 'reaction' or char_length(content) <= 32)
    ),
  created_at timestamptz not null default now(),
  constraint dp_chat_messages_participant_fk
    foreign key (participant_id, room_id)
    references public.dp_participants(id, room_id)
    on delete cascade
);

create index dp_chat_messages_room_created_idx
  on public.dp_chat_messages (room_id, created_at desc);

create table private.dp_game_state (
  room_id uuid primary key references public.dp_rooms(id) on delete cascade,
  version bigint not null default 0 check (version >= 0),
  state jsonb not null default '{}'::jsonb
    check (jsonb_typeof(state) = 'object'),
  updated_at timestamptz not null default now()
);

create table private.dp_guest_sessions (
  token_hash text primary key
    check (token_hash ~ '^[0-9a-f]{64}$'),
  room_id uuid not null,
  participant_id uuid not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  constraint dp_guest_sessions_participant_fk
    foreign key (participant_id, room_id)
    references public.dp_participants(id, room_id)
    on delete cascade,
  constraint dp_guest_sessions_expiry_check check (expires_at > created_at)
);

create unique index dp_guest_sessions_active_participant_idx
  on private.dp_guest_sessions (room_id, participant_id)
  where revoked_at is null;

create index dp_guest_sessions_expiry_idx
  on private.dp_guest_sessions (expires_at)
  where revoked_at is null;

create table private.dp_join_limits (
  key_hash text primary key
    check (key_hash ~ '^[0-9a-f]{64}$'),
  window_started_at timestamptz not null default now(),
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

create index dp_join_limits_cleanup_idx
  on private.dp_join_limits (updated_at, blocked_until);

alter table public.dp_rooms enable row level security;
alter table public.dp_rooms force row level security;
alter table public.dp_participants enable row level security;
alter table public.dp_participants force row level security;
alter table public.dp_public_state enable row level security;
alter table public.dp_public_state force row level security;
alter table public.dp_action_log enable row level security;
alter table public.dp_action_log force row level security;
alter table public.dp_chat_messages enable row level security;
alter table public.dp_chat_messages force row level security;
alter table private.dp_game_state enable row level security;
alter table private.dp_game_state force row level security;
alter table private.dp_guest_sessions enable row level security;
alter table private.dp_guest_sessions force row level security;
alter table private.dp_join_limits enable row level security;
alter table private.dp_join_limits force row level security;

revoke all on table
  public.dp_rooms,
  public.dp_participants,
  public.dp_public_state,
  public.dp_action_log,
  public.dp_chat_messages
from public, anon, authenticated;

revoke all on table
  private.dp_game_state,
  private.dp_guest_sessions,
  private.dp_join_limits
from public, anon, authenticated;

grant all on table
  public.dp_rooms,
  public.dp_participants,
  public.dp_public_state,
  public.dp_action_log,
  public.dp_chat_messages
to service_role;

grant all on table
  private.dp_game_state,
  private.dp_guest_sessions,
  private.dp_join_limits
to service_role;

create trigger dp_rooms_touch_updated_at
before update on public.dp_rooms
for each row execute function private.dp_touch_updated_at();

create or replace function private.dp_record_join_failure(
  p_key_hash text,
  p_max_attempts integer,
  p_window interval,
  p_block interval
)
returns table (
  allowed boolean,
  retry_after_seconds integer,
  failed_attempts integer
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_attempts integer;
  v_blocked_until timestamptz;
begin
  if p_key_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'invalid_rate_key';
  end if;
  if p_max_attempts < 1 or p_max_attempts > 100 then
    raise exception using errcode = '22023', message = 'invalid_max_attempts';
  end if;
  if p_window <= interval '0 seconds' or p_block <= interval '0 seconds' then
    raise exception using errcode = '22023', message = 'invalid_rate_limit_interval';
  end if;

  insert into private.dp_join_limits as join_limit (
    key_hash,
    window_started_at,
    failed_attempts,
    blocked_until,
    updated_at
  )
  values (
    p_key_hash,
    v_now,
    1,
    case when p_max_attempts = 1 then v_now + p_block end,
    v_now
  )
  on conflict (key_hash) do update
  set
    window_started_at = case
      when join_limit.window_started_at <= v_now - p_window then v_now
      else join_limit.window_started_at
    end,
    failed_attempts = case
      when join_limit.window_started_at <= v_now - p_window then 1
      else join_limit.failed_attempts + 1
    end,
    blocked_until = case
      when join_limit.blocked_until > v_now then join_limit.blocked_until
      when (
        case
          when join_limit.window_started_at <= v_now - p_window then 1
          else join_limit.failed_attempts + 1
        end
      ) >= p_max_attempts then v_now + p_block
      else null
    end,
    updated_at = v_now
  returning join_limit.failed_attempts, join_limit.blocked_until
  into v_attempts, v_blocked_until;

  return query
  select
    v_blocked_until is null or v_blocked_until <= v_now,
    case
      when v_blocked_until > v_now
        then greatest(1, ceil(extract(epoch from v_blocked_until - v_now))::integer)
      else 0
    end,
    v_attempts;
end;
$$;

create or replace function public.dp_create_room(
  p_room_id uuid,
  p_public_id uuid,
  p_code_hash text,
  p_broadcast_topic text,
  p_owner_participant_id uuid,
  p_owner_clerk_user_id text,
  p_owner_display_name text,
  p_max_seats smallint,
  p_starting_stack bigint,
  p_small_blind bigint,
  p_big_blind bigint,
  p_action_timeout_seconds smallint,
  p_initial_private_state jsonb,
  p_initial_public_state jsonb
)
returns table (
  room_id uuid,
  public_id uuid,
  broadcast_topic text,
  owner_participant_id uuid,
  version bigint,
  expires_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_room_id uuid;
  v_owner_participant_id uuid;
  v_public_id uuid;
  v_broadcast_topic text;
  v_expires_at timestamptz;
begin
  if p_room_id is null or p_public_id is null or p_owner_participant_id is null then
    raise exception using errcode = '22023', message = 'invalid_identifier';
  end if;
  if p_code_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'invalid_code_hash';
  end if;
  if p_broadcast_topic !~ '^[0-9A-Za-z_-]{32,96}$' then
    raise exception using errcode = '22023', message = 'invalid_broadcast_topic';
  end if;
  if jsonb_typeof(p_initial_private_state) is distinct from 'object'
    or p_initial_private_state ->> 'version' is distinct from '0'
    or p_initial_private_state ->> 'tableId' is distinct from p_room_id::text
    or p_initial_private_state #>> '{config,maxSeats}' is distinct from p_max_seats::text
    or p_initial_private_state #>> '{config,startingStack}' is distinct from p_starting_stack::text
    or p_initial_private_state #>> '{config,smallBlind}' is distinct from p_small_blind::text
    or p_initial_private_state #>> '{config,bigBlind}' is distinct from p_big_blind::text
    or p_initial_private_state #>> '{config,actionTimeoutMs}'
      is distinct from (p_action_timeout_seconds::bigint * 1000)::text
    or jsonb_typeof(p_initial_private_state -> 'players') is distinct from 'array' then
    raise exception using errcode = '22023', message = 'invalid_initial_private_state';
  end if;
  if not exists (
    select 1
    from jsonb_array_elements(p_initial_private_state -> 'players') as player(value)
    where player.value ->> 'id' = p_owner_participant_id::text
  ) then
    raise exception using errcode = '22023', message = 'initial_owner_missing';
  end if;
  if not private.dp_public_payload_is_safe(p_initial_public_state)
    or (
      p_initial_public_state ? 'version'
      and p_initial_public_state ->> 'version' is distinct from '0'
    ) then
    raise exception using errcode = '22023', message = 'invalid_initial_public_state';
  end if;

  -- Do not let an already elapsed room wait for the hourly cron before the
  -- one-open-room unique index permits its replacement.
  update public.dp_rooms
  set
    status = 'expired',
    locked = true,
    closed_at = coalesce(closed_at, now())
  where status in ('lobby', 'active', 'paused')
    and expires_at <= now();

  insert into public.dp_rooms as created_room (
    id,
    public_id,
    code_hash,
    broadcast_topic,
    owner_clerk_user_id,
    max_seats,
    starting_stack,
    small_blind,
    big_blind,
    action_timeout_seconds,
    expires_at
  )
  values (
    p_room_id,
    p_public_id,
    p_code_hash,
    p_broadcast_topic,
    p_owner_clerk_user_id,
    p_max_seats,
    p_starting_stack,
    p_small_blind,
    p_big_blind,
    p_action_timeout_seconds,
    now() + interval '12 hours'
  )
  returning created_room.id, created_room.public_id, created_room.broadcast_topic,
    created_room.expires_at
  into v_room_id, v_public_id, v_broadcast_topic, v_expires_at;

  insert into public.dp_participants (
    id,
    room_id,
    kind,
    clerk_user_id,
    display_name,
    role,
    seat,
    stack,
    connected,
    ready,
    sitting_out,
    status
  )
  values (
    p_owner_participant_id,
    v_room_id,
    'owner',
    p_owner_clerk_user_id,
    p_owner_display_name,
    'player',
    1,
    p_starting_stack,
    true,
    true,
    false,
    'ready'
  )
  returning id into v_owner_participant_id;

  insert into private.dp_game_state (room_id, version, state)
  values (v_room_id, 0, p_initial_private_state);

  insert into public.dp_public_state (room_id, version, kind, state)
  values (v_room_id, 0, 'room_created', p_initial_public_state);

  return query
  select
    v_room_id,
    v_public_id,
    v_broadcast_topic,
    v_owner_participant_id,
    0::bigint,
    v_expires_at;
end;
$$;

create or replace function public.dp_join_room(
  p_code_hash text,
  p_display_name text,
  p_role text,
  p_token_hash text,
  p_rate_key_hash text
)
returns table (
  accepted boolean,
  reason text,
  retry_after_seconds integer,
  room_id uuid,
  public_id uuid,
  participant_id uuid,
  broadcast_topic text,
  expires_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_room public.dp_rooms%rowtype;
  v_participant_id uuid;
  v_seat smallint;
  v_retry integer := 0;
  v_attempts integer := 0;
  v_allowed boolean := true;
  v_blocked_until timestamptz;
begin
  if p_code_hash !~ '^[0-9a-f]{64}$'
    or p_token_hash !~ '^[0-9a-f]{64}$'
    or p_rate_key_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'invalid_digest';
  end if;
  if p_role not in ('player', 'spectator') then
    raise exception using errcode = '22023', message = 'invalid_role';
  end if;
  if char_length(p_display_name) not between 1 and 24
    or p_display_name <> btrim(p_display_name)
    or p_display_name ~ '[[:cntrl:]]' then
    raise exception using errcode = '22023', message = 'invalid_display_name';
  end if;

  select join_limit.blocked_until
  into v_blocked_until
  from private.dp_join_limits as join_limit
  where join_limit.key_hash = p_rate_key_hash
  for update;

  if v_blocked_until > v_now then
    return query
    select
      false,
      'rate_limited'::text,
      greatest(1, ceil(extract(epoch from v_blocked_until - v_now))::integer),
      null::uuid,
      null::uuid,
      null::uuid,
      null::text,
      null::timestamptz;
    return;
  end if;

  select room.*
  into v_room
  from public.dp_rooms as room
  where room.code_hash = p_code_hash
    and room.status in ('lobby', 'active', 'paused')
    and room.expires_at > v_now
  for update;

  if not found then
    select failure.allowed, failure.retry_after_seconds, failure.failed_attempts
    into v_allowed, v_retry, v_attempts
    from private.dp_record_join_failure(
      p_rate_key_hash,
      5,
      interval '10 minutes',
      interval '30 minutes'
    ) as failure;

    return query
    select
      false,
      case when v_allowed then 'invalid_invite' else 'rate_limited' end,
      v_retry,
      null::uuid,
      null::uuid,
      null::uuid,
      null::text,
      null::timestamptz;
    return;
  end if;

  if v_room.locked then
    return query
    select false, 'room_locked'::text, 0,
      null::uuid, null::uuid, null::uuid, null::text, null::timestamptz;
    return;
  end if;

  if p_role = 'spectator' and not v_room.spectators_enabled then
    return query
    select false, 'spectators_disabled'::text, 0,
      null::uuid, null::uuid, null::uuid, null::text, null::timestamptz;
    return;
  end if;

  if exists (
    select 1
    from public.dp_participants as participant
    where participant.room_id = v_room.id
      and lower(participant.display_name) = lower(p_display_name)
      and participant.status not in ('left', 'kicked')
  ) then
    return query
    select false, 'nickname_taken'::text, 0,
      null::uuid, null::uuid, null::uuid, null::text, null::timestamptz;
    return;
  end if;

  if p_role = 'player' then
    select available_seat.seat::smallint
    into v_seat
    from generate_series(1, v_room.max_seats) as available_seat(seat)
    where not exists (
      select 1
      from public.dp_participants as participant
      where participant.room_id = v_room.id
        and participant.seat = available_seat.seat
        and participant.status not in ('left', 'kicked')
    )
    order by available_seat.seat
    limit 1;

    if v_seat is null then
      return query
      select false, 'room_full'::text, 0,
        null::uuid, null::uuid, null::uuid, null::text, null::timestamptz;
      return;
    end if;
  end if;

  insert into public.dp_participants (
    room_id,
    kind,
    display_name,
    role,
    seat,
    stack,
    status
  )
  values (
    v_room.id,
    'guest',
    p_display_name,
    p_role,
    v_seat,
    case when p_role = 'player' then v_room.starting_stack else 0 end,
    'joined'
  )
  returning id into v_participant_id;

  insert into private.dp_guest_sessions (
    token_hash,
    room_id,
    participant_id,
    expires_at
  )
  values (
    p_token_hash,
    v_room.id,
    v_participant_id,
    v_room.expires_at
  );

  delete from private.dp_join_limits
  where key_hash = p_rate_key_hash;

  return query
  select
    true,
    'joined'::text,
    0,
    v_room.id,
    v_room.public_id,
    v_participant_id,
    v_room.broadcast_topic,
    v_room.expires_at;
end;
$$;

create or replace function public.dp_get_game_state(p_room_id uuid)
returns table (version bigint, state jsonb)
language sql
stable
security invoker
set search_path = ''
as $$
  select game_state.version, game_state.state
  from private.dp_game_state as game_state
  where game_state.room_id = p_room_id;
$$;

create or replace function public.dp_resolve_guest_session(
  p_room_id uuid,
  p_token_hash text
)
returns table (
  participant_id uuid,
  role text,
  status text,
  expires_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    return;
  end if;

  update private.dp_guest_sessions as guest_session
  set last_seen_at = now()
  from public.dp_rooms as room,
       public.dp_participants as participant
  where guest_session.token_hash = p_token_hash
    and guest_session.room_id = p_room_id
    and guest_session.room_id = room.id
    and guest_session.participant_id = participant.id
    and participant.room_id = room.id
    and guest_session.revoked_at is null
    and guest_session.expires_at > now()
    and room.expires_at > now()
    and room.status in ('lobby', 'active', 'paused')
    and participant.status not in ('left', 'kicked');

  update public.dp_participants as participant
  set last_seen_at = now()
  from private.dp_guest_sessions as guest_session
  where guest_session.token_hash = p_token_hash
    and guest_session.room_id = p_room_id
    and guest_session.participant_id = participant.id
    and guest_session.revoked_at is null
    and guest_session.expires_at > now();

  return query
  select
    participant.id,
    participant.role,
    participant.status,
    guest_session.expires_at
  from private.dp_guest_sessions as guest_session
  join public.dp_participants as participant
    on participant.id = guest_session.participant_id
   and participant.room_id = guest_session.room_id
  join public.dp_rooms as room
    on room.id = guest_session.room_id
  where guest_session.token_hash = p_token_hash
    and guest_session.room_id = p_room_id
    and guest_session.revoked_at is null
    and guest_session.expires_at > now()
    and room.expires_at > now()
    and room.status in ('lobby', 'active', 'paused')
    and participant.status not in ('left', 'kicked');
end;
$$;

create or replace function public.dp_revoke_guest_session(
  p_room_id uuid,
  p_participant_id uuid
)
returns void
language sql
security invoker
set search_path = ''
as $$
  update private.dp_guest_sessions
  set revoked_at = coalesce(revoked_at, now())
  where room_id = p_room_id
    and participant_id = p_participant_id
    and revoked_at is null;
$$;

create or replace function public.dp_register_join_failure(
  p_key_hash text,
  p_max_attempts integer default 5,
  p_window interval default interval '10 minutes',
  p_block interval default interval '30 minutes'
)
returns table (
  allowed boolean,
  retry_after_seconds integer,
  failed_attempts integer
)
language sql
security invoker
set search_path = ''
as $$
  select failure.allowed, failure.retry_after_seconds, failure.failed_attempts
  from private.dp_record_join_failure(
    p_key_hash,
    p_max_attempts,
    p_window,
    p_block
  ) as failure;
$$;

create or replace function public.dp_clear_join_limit(p_key_hash text)
returns void
language sql
security invoker
set search_path = ''
as $$
  delete from private.dp_join_limits
  where key_hash = p_key_hash;
$$;

create or replace function public.dp_commit_state(
  p_room_id uuid,
  p_action_id uuid,
  p_expected_version bigint,
  p_actor_participant_id uuid,
  p_action_kind text,
  p_private_state jsonb,
  p_public_state jsonb,
  p_action_metadata jsonb default '{}'::jsonb
)
returns table (version bigint, applied boolean)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_room_version bigint;
  v_room_status text;
  v_room_expires_at timestamptz;
  v_existing_room_id uuid;
  v_existing_version bigint;
  v_existing_request_hash text;
  v_request_hash text;
  v_next_version bigint;
  v_game_status text;
begin
  if p_action_id is null then
    raise exception using errcode = '22023', message = 'invalid_action_id';
  end if;
  if p_expected_version < 0 then
    raise exception using errcode = '22023', message = 'invalid_expected_version';
  end if;
  if p_action_kind !~ '^[a-z][a-z0-9_]{0,39}$' then
    raise exception using errcode = '22023', message = 'invalid_action_kind';
  end if;
  if not private.dp_public_payload_is_safe(p_public_state)
    or not private.dp_public_payload_is_safe(p_action_metadata) then
    raise exception using errcode = '22023', message = 'unsafe_public_payload';
  end if;
  if jsonb_typeof(p_private_state) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_private_state';
  end if;
  if coalesce(p_private_state ->> 'version', '') !~ '^[0-9]+$' then
    raise exception using errcode = '22023', message = 'invalid_private_state_version';
  end if;

  v_next_version := (p_private_state ->> 'version')::bigint;
  if v_next_version <= p_expected_version then
    raise exception using errcode = '22023', message = 'non_monotonic_state_version';
  end if;
  if p_public_state ? 'version'
    and coalesce(p_public_state ->> 'version', '') !~ '^[0-9]+$' then
    raise exception using errcode = '22023', message = 'invalid_public_state_version';
  end if;
  if p_public_state ? 'version'
    and (p_public_state ->> 'version')::bigint <> v_next_version then
    raise exception using errcode = '22023', message = 'public_state_version_mismatch';
  end if;
  if coalesce(p_private_state #>> '{config,maxSeats}', '') !~ '^[0-9]+$'
    or coalesce(p_private_state #>> '{config,startingStack}', '') !~ '^[0-9]+$'
    or coalesce(p_private_state #>> '{config,smallBlind}', '') !~ '^[0-9]+$'
    or coalesce(p_private_state #>> '{config,bigBlind}', '') !~ '^[0-9]+$'
    or coalesce(p_private_state #>> '{config,actionTimeoutMs}', '') !~ '^[0-9]+$' then
    raise exception using errcode = '22023', message = 'invalid_game_config';
  end if;
  if (p_private_state #>> '{config,actionTimeoutMs}')::bigint % 1000 <> 0 then
    raise exception using errcode = '22023', message = 'invalid_game_config';
  end if;

  v_request_hash := encode(
    sha256(convert_to(
      jsonb_build_object(
        'roomId', p_room_id,
        'expectedVersion', p_expected_version,
        'actorParticipantId', p_actor_participant_id,
        'actionKind', p_action_kind,
        'privateState', p_private_state,
        'publicState', p_public_state,
        'actionMetadata', p_action_metadata
      )::text,
      'UTF8'
    )),
    'hex'
  );

  select room.version, room.status, room.expires_at
  into v_room_version, v_room_status, v_room_expires_at
  from public.dp_rooms as room
  where room.id = p_room_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'room_not_available';
  end if;

  select action_log.room_id, action_log.resulting_version, action_log.request_hash
  into v_existing_room_id, v_existing_version, v_existing_request_hash
  from public.dp_action_log as action_log
  where action_log.action_id = p_action_id;

  if found then
    if v_existing_room_id <> p_room_id or v_existing_request_hash <> v_request_hash then
      raise exception using errcode = '23505', message = 'action_id_reused';
    end if;
    return query select v_existing_version, false;
    return;
  end if;

  if v_room_status in ('closed', 'expired') or v_room_expires_at <= now() then
    raise exception using errcode = 'P0002', message = 'room_not_available';
  end if;

  if v_room_version <> p_expected_version then
    raise exception using
      errcode = '40001',
      message = 'state_version_conflict',
      detail = format('expected=%s actual=%s', p_expected_version, v_room_version);
  end if;

  if p_actor_participant_id is not null and not exists (
    select 1
    from public.dp_participants as participant
    where participant.id = p_actor_participant_id
      and participant.room_id = p_room_id
      and participant.status not in ('left', 'kicked')
  ) then
    raise exception using errcode = '22023', message = 'invalid_actor';
  end if;

  if not exists (
    select 1
    from private.dp_game_state as game_state
    where game_state.room_id = p_room_id
      and game_state.version = p_expected_version
  ) or not exists (
    select 1
    from public.dp_public_state as public_state
    where public_state.room_id = p_room_id
      and public_state.version = p_expected_version
  ) then
    raise exception using errcode = '40001', message = 'state_storage_version_conflict';
  end if;

  update private.dp_game_state
  set
    version = v_next_version,
    state = p_private_state,
    updated_at = now()
  where room_id = p_room_id;

  update public.dp_public_state
  set
    version = v_next_version,
    kind = p_action_kind,
    state = p_public_state,
    updated_at = now()
  where room_id = p_room_id;

  v_game_status := p_private_state ->> 'status';
  if v_game_status is null
    or v_game_status not in ('waiting', 'playing', 'paused', 'closed') then
    raise exception using errcode = '22023', message = 'invalid_game_status';
  end if;
  with player_updates as (
    select
      (player.value ->> 'id')::uuid as participant_id,
      (player.value ->> 'stack')::bigint as stack,
      coalesce((player.value ->> 'connected')::boolean, false) as connected,
      coalesce((player.value ->> 'ready')::boolean, false) as ready,
      coalesce((player.value ->> 'sittingOut')::boolean, false) as sitting_out,
      (
        select hand_player.value ->> 'status'
        from jsonb_array_elements(
          case
            when jsonb_typeof(p_private_state #> '{hand,players}') = 'array'
              then p_private_state #> '{hand,players}'
            else '[]'::jsonb
          end
        ) as hand_player(value)
        where hand_player.value ->> 'playerId' = player.value ->> 'id'
        limit 1
      ) as hand_status
    from jsonb_array_elements(
      case
        when jsonb_typeof(p_private_state -> 'players') = 'array'
          then p_private_state -> 'players'
        else '[]'::jsonb
      end
    ) as player(value)
  )
  update public.dp_participants as participant
  set
    stack = player_update.stack,
    connected = player_update.connected,
    ready = player_update.ready,
    sitting_out = player_update.sitting_out,
    status = case
      when player_update.sitting_out then 'sitting_out'
      when player_update.hand_status = 'all-in' then 'all_in'
      when player_update.hand_status = 'folded' then 'folded'
      when player_update.hand_status = 'active' then 'active'
      when player_update.ready then 'ready'
      else 'joined'
    end
  from player_updates as player_update
  where participant.id = player_update.participant_id
    and participant.room_id = p_room_id
    and participant.role = 'player'
    and participant.status not in ('left', 'kicked');

  update public.dp_rooms
  set
    version = v_next_version,
    max_seats = (p_private_state #>> '{config,maxSeats}')::smallint,
    starting_stack = (p_private_state #>> '{config,startingStack}')::bigint,
    small_blind = (p_private_state #>> '{config,smallBlind}')::bigint,
    big_blind = (p_private_state #>> '{config,bigBlind}')::bigint,
    action_timeout_seconds = (
      (p_private_state #>> '{config,actionTimeoutMs}')::bigint / 1000
    )::smallint,
    status = case
      when v_game_status = 'playing' then 'active'
      when v_game_status = 'paused' then 'paused'
      when v_game_status = 'closed' then 'closed'
      else 'lobby'
    end,
    pause_after_hand = case
      when v_game_status in ('paused', 'closed') then false
      else pause_after_hand
    end,
    closed_at = case
      when v_game_status = 'closed' then coalesce(closed_at, now())
      else closed_at
    end
  where id = p_room_id;

  insert into public.dp_action_log (
    action_id,
    room_id,
    participant_id,
    action_kind,
    request_hash,
    expected_version,
    resulting_version,
    metadata
  )
  values (
    p_action_id,
    p_room_id,
    p_actor_participant_id,
    p_action_kind,
    v_request_hash,
    p_expected_version,
    v_next_version,
    p_action_metadata
  );

  return query select v_next_version, true;
end;
$$;

-- Realtime's own schema is intentionally not modified. This trigger calls the
-- supported realtime.send API and publishes only a version hint on a random,
-- unguessable topic. The client refetches authorized state over Next.js.
create or replace function public.dp_broadcast_state_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_topic text;
begin
  select room.broadcast_topic
  into v_topic
  from public.dp_rooms as room
  where room.id = new.room_id;

  if v_topic is not null then
    perform realtime.send(
      jsonb_build_object('version', new.version, 'kind', new.kind),
      'state',
      'dp:' || v_topic,
      false
    );
  end if;

  return new;
end;
$$;

create trigger dp_public_state_broadcast
after insert or update of version, kind on public.dp_public_state
for each row execute function public.dp_broadcast_state_change();

create or replace function public.dp_cleanup_expired_data()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.dp_rooms
  set
    status = 'expired',
    closed_at = coalesce(closed_at, now()),
    locked = true
  where status in ('lobby', 'active', 'paused')
    and expires_at <= now();

  update private.dp_guest_sessions as guest_session
  set revoked_at = coalesce(guest_session.revoked_at, now())
  where guest_session.revoked_at is null
    and (
      guest_session.expires_at <= now()
      or exists (
        select 1
        from public.dp_rooms as room
        where room.id = guest_session.room_id
          and room.status in ('closed', 'expired')
      )
    );

  delete from public.dp_chat_messages as message
  using public.dp_rooms as room
  where message.room_id = room.id
    and room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours';

  delete from public.dp_public_state as public_state
  using public.dp_rooms as room
  where public_state.room_id = room.id
    and room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours';

  delete from private.dp_game_state as game_state
  using public.dp_rooms as room
  where game_state.room_id = room.id
    and room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours';

  delete from private.dp_guest_sessions as guest_session
  using public.dp_rooms as room
  where guest_session.room_id = room.id
    and room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours';

  -- Keep only the minimum 30-day operational audit. Names, settlements and
  -- the owner's external identity are no longer needed after secret state is purged.
  update public.dp_action_log as action_log
  set metadata = '{}'::jsonb
  from public.dp_rooms as room
  where action_log.room_id = room.id
    and room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours'
    and action_log.metadata <> '{}'::jsonb;

  update public.dp_rooms as room
  set
    owner_clerk_user_id = 'purged',
    code_hash = encode(digest('purged:' || room.id::text, 'sha256'), 'hex')
  where room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours'
    and room.owner_clerk_user_id <> 'purged';

  delete from public.dp_participants as participant
  using public.dp_rooms as room
  where participant.room_id = room.id
    and room.status in ('closed', 'expired')
    and coalesce(room.closed_at, room.expires_at) <= now() - interval '24 hours';

  delete from private.dp_join_limits
  where updated_at <= now() - interval '24 hours'
    and (blocked_until is null or blocked_until <= now());

  delete from public.dp_rooms
  where status in ('closed', 'expired')
    and coalesce(closed_at, expires_at) <= now() - interval '30 days';
end;
$$;

revoke all on function private.dp_public_payload_is_safe(jsonb)
  from public, anon, authenticated;
revoke all on function private.dp_touch_updated_at()
  from public, anon, authenticated;
revoke all on function private.dp_record_join_failure(text, integer, interval, interval)
  from public, anon, authenticated;
revoke all on function public.dp_create_room(
  uuid, uuid, text, text, uuid, text, text, smallint, bigint, bigint, bigint, smallint, jsonb, jsonb
) from public, anon, authenticated;
revoke all on function public.dp_join_room(text, text, text, text, text)
  from public, anon, authenticated;
revoke all on function public.dp_get_game_state(uuid)
  from public, anon, authenticated;
revoke all on function public.dp_resolve_guest_session(uuid, text)
  from public, anon, authenticated;
revoke all on function public.dp_revoke_guest_session(uuid, uuid)
  from public, anon, authenticated;
revoke all on function public.dp_register_join_failure(text, integer, interval, interval)
  from public, anon, authenticated;
revoke all on function public.dp_clear_join_limit(text)
  from public, anon, authenticated;
revoke all on function public.dp_commit_state(
  uuid, uuid, bigint, uuid, text, jsonb, jsonb, jsonb
) from public, anon, authenticated;
revoke all on function public.dp_broadcast_state_change()
  from public, anon, authenticated;
revoke all on function public.dp_cleanup_expired_data()
  from public, anon, authenticated;

grant execute on function private.dp_public_payload_is_safe(jsonb)
  to service_role;
grant execute on function private.dp_touch_updated_at()
  to service_role;
grant execute on function private.dp_record_join_failure(text, integer, interval, interval)
  to service_role;
grant execute on function public.dp_create_room(
  uuid, uuid, text, text, uuid, text, text, smallint, bigint, bigint, bigint, smallint, jsonb, jsonb
) to service_role;
grant execute on function public.dp_join_room(text, text, text, text, text)
  to service_role;
grant execute on function public.dp_get_game_state(uuid)
  to service_role;
grant execute on function public.dp_resolve_guest_session(uuid, text)
  to service_role;
grant execute on function public.dp_revoke_guest_session(uuid, uuid)
  to service_role;
grant execute on function public.dp_register_join_failure(text, integer, interval, interval)
  to service_role;
grant execute on function public.dp_clear_join_limit(text)
  to service_role;
grant execute on function public.dp_commit_state(
  uuid, uuid, bigint, uuid, text, jsonb, jsonb, jsonb
) to service_role;
grant execute on function public.dp_broadcast_state_change()
  to service_role;
grant execute on function public.dp_cleanup_expired_data()
  to service_role;

select cron.schedule(
  'dp-cleanup-hourly',
  '17 * * * *',
  $$select public.dp_cleanup_expired_data();$$
)
where not exists (
  select 1
  from cron.job
  where jobname = 'dp-cleanup-hourly'
);

commit;
